# Generated by Django 6.0.5 on 2026-06-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_longest_streak_user_streak_user_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
