# Generated by Django 6.0.5 on 2026-06-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_study_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_completed_today',
            field=models.BooleanField(default=False),
        ),
    ]
