# Generated by Django 6.0.5 on 2026-06-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_study_completed_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
